name: Scheduled job (no deployment)

on:
  schedule:
    - cron: '5 20 * * *'    

jobs:
  job-name:
    runs-on: ubuntu-latest
    environment:
      deployment: false
      name: dev
    steps:
      - run: echo 'done'  
